version = 5.1.0
archive_dir = /etc/letsencrypt/archive/aizhao.icu
cert = /etc/letsencrypt/live/aizhao.icu/cert.pem
privkey = /etc/letsencrypt/live/aizhao.icu/privkey.pem
chain = /etc/letsencrypt/live/aizhao.icu/chain.pem
fullchain = /etc/letsencrypt/live/aizhao.icu/fullchain.pem
[renewalparams]
account = 954131894b3e7e5030cb827b4f123f99
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
admin.aizhao.icu = /var/www/certbot
aizhao.icu = /var/www/certbot
api.aizhao.icu = /var/www/certbot
www.aizhao.icu = /var/www/certbot
