/**
 * 统一错误码定义
 *
 * 按模块和类型分类，便于国际化翻译
 */

// 通用错误码 (1000-1999)
export const COMMON_ERRORS = {
  SUCCESS: 0,
  UNKNOWN_ERROR: 1000,
  INVALID_REQUEST: 1001,
  MISSING_PARAMETERS: 1002,
  INVALID_PARAMETERS: 1003,
  RATE_LIMIT_EXCEEDED: 1004,
  INTERNAL_SERVER_ERROR: 1500,
  DATABASE_ERROR: 1501,
  CACHE_ERROR: 1502,
  QUEUE_ERROR: 1503,
  EXTERNAL_SERVICE_ERROR: 1504
} as const;

// 认证授权错误码 (2000-2999)
export const AUTH_ERRORS = {
  // 认证相关 (2000-2099)
  UNAUTHORIZED: 2000,
  INVALID_TOKEN: 2001,
  TOKEN_EXPIRED: 2002,
  TOKEN_BLACKLISTED: 2003,
  INVALID_CREDENTIALS: 2004,
  ACCOUNT_LOCKED: 2005,
  ACCOUNT_DISABLED: 2006,
  ACCOUNT_NOT_FOUND: 2007,
  PASSWORD_INCORRECT: 2008,
  LOGIN_REQUIRED: 2009,

  // 登录相关 (2100-2199)
  LOGIN_ATTEMPTS_EXCEEDED: 2100,
  LOGIN_METHOD_NOT_SUPPORTED: 2101,
  LOGIN_METHOD_NOT_BOUND: 2102,
  VERIFICATION_CODE_INVALID: 2103,
  VERIFICATION_CODE_EXPIRED: 2104,
  VERIFICATION_SEND_LIMIT: 2105,
  EMAIL_ALREADY_EXISTS: 2106,
  PHONE_ALREADY_EXISTS: 2107,
  SOCIAL_LOGIN_FAILED: 2108,

  // 权限相关 (2200-2299)
  PERMISSION_DENIED: 2200,
  INSUFFICIENT_PERMISSIONS: 2201,
  ROLE_NOT_FOUND: 2202,
  ROLE_ASSIGNMENT_FAILED: 2203,
  RESOURCE_ACCESS_DENIED: 2204,
  ADMIN_REQUIRED: 2205
} as const;

// 用户管理错误码 (3000-3999)
export const USER_ERRORS = {
  USER_NOT_FOUND: 3000,
  USER_ALREADY_EXISTS: 3001,
  USER_PROFILE_INCOMPLETE: 3002,
  USER_QUOTA_EXCEEDED: 3003,
  USER_MEMBERSHIP_EXPIRED: 3004,
  USER_SUBSCRIPTION_INACTIVE: 3005,
  INVITE_CODE_INVALID: 3006,
  INVITE_CODE_USED: 3007,
  INVITE_CODE_EXPIRED: 3008,
  REFERRAL_CODE_INVALID: 3009,
  REFERRAL_NOT_FOUND: 3010
} as const;

// 任务处理错误码 (4000-4999)
export const TASK_ERRORS = {
  TASK_NOT_FOUND: 4000,
  TASK_CREATION_FAILED: 4001,
  TASK_PROCESSING_FAILED: 4002,
  TASK_TIMEOUT: 4003,
  TASK_CANCELLED: 4004,
  TASK_QUOTA_EXCEEDED: 4005,
  TASK_INVALID_PARAMETERS: 4006,
  TASK_PROCESSOR_UNAVAILABLE: 4007,
  TASK_DEPENDENCY_FAILED: 4008,
  TASK_RESULT_EXPIRED: 4009,

  // 文件相关 (4100-4199)
  FILE_NOT_FOUND: 4100,
  FILE_TOO_LARGE: 4101,
  FILE_TYPE_NOT_SUPPORTED: 4102,
  FILE_UPLOAD_FAILED: 4103,
  FILE_PROCESSING_FAILED: 4104,
  FILE_DOWNLOAD_FAILED: 4105,
  FILE_CORRUPTED: 4106,
  STORAGE_QUOTA_EXCEEDED: 4107,

  // AI处理相关 (4200-4299)
  AI_PROCESSING_FAILED: 4200,
  AI_SERVICE_UNAVAILABLE: 4201,
  AI_QUOTA_EXCEEDED: 4202,
  AI_CONTENT_POLICY_VIOLATION: 4203,
  AI_PROCESSING_TIMEOUT: 4204,
  AI_INVALID_INPUT_FORMAT: 4205
} as const;

// 支付相关错误码 (5000-5999)
export const PAYMENT_ERRORS = {
  PAYMENT_REQUIRED: 5000,
  PAYMENT_FAILED: 5001,
  PAYMENT_CANCELLED: 5002,
  PAYMENT_TIMEOUT: 5003,
  PAYMENT_METHOD_NOT_SUPPORTED: 5004,
  ORDER_NOT_FOUND: 5005,
  ORDER_EXPIRED: 5006,
  ORDER_ALREADY_PAID: 5007,
  REFUND_FAILED: 5008,
  REFUND_AMOUNT_INVALID: 5009,
  PAYMENT_GATEWAY_ERROR: 5010,
  INSUFFICIENT_BALANCE: 5011,
  PAYMENT_VERIFICATION_FAILED: 5012
} as const;

// 分销系统错误码 (6000-6999)
export const DISTRIBUTION_ERRORS = {
  DISTRIBUTOR_NOT_FOUND: 6000,
  DISTRIBUTION_NOT_ACTIVE: 6001,
  COMMISSION_CALCULATION_FAILED: 6002,
  WITHDRAWAL_FAILED: 6003,
  WITHDRAWAL_AMOUNT_INVALID: 6004,
  WITHDRAWAL_LIMIT_EXCEEDED: 6005,
  DISTRIBUTION_RULE_NOT_FOUND: 6006,
  COMMISSION_FREEZE_FAILED: 6007,
  COMMISSION_UNFREEZE_FAILED: 6008
} as const;

// 系统配置错误码 (7000-7999)
export const SYSTEM_ERRORS = {
  CONFIG_NOT_FOUND: 7000,
  CONFIG_VALIDATION_FAILED: 7001,
  FEATURE_NOT_ENABLED: 7002,
  FEATURE_NOT_AVAILABLE: 7003,
  SYSTEM_MAINTENANCE: 7004,
  SERVICE_UNAVAILABLE: 7005,
  RATE_LIMIT_CONFIG_INVALID: 7006,
  CACHE_VERSION_CONFLICT: 7007,
  DATABASE_MIGRATION_FAILED: 7008,
  ENVIRONMENT_VARIABLE_MISSING: 7009
} as const;

// 网络与通信错误码 (8000-8999)
export const NETWORK_ERRORS = {
  CONNECTION_FAILED: 8000,
  REQUEST_TIMEOUT: 8001,
  DNS_RESOLUTION_FAILED: 8002,
  SSL_VERIFICATION_FAILED: 8003,
  PROXY_ERROR: 8004,
  BANDWIDTH_LIMIT_EXCEEDED: 8005,
  WEBSOCKET_CONNECTION_FAILED: 8006,
  NOTIFICATION_SEND_FAILED: 8007
} as const;

// 数据验证错误码 (9000-9999)
export const VALIDATION_ERRORS = {
  DATA_VALIDATION_FAILED: 9000,
  EMAIL_FORMAT_INVALID: 9001,
  PHONE_FORMAT_INVALID: 9002,
  PASSWORD_TOO_WEAK: 9003,
  PASSWORD_MISMATCH: 9004,
  URL_FORMAT_INVALID: 9005,
  DATE_FORMAT_INVALID: 9006,
  NUMBER_OUT_OF_RANGE: 9007,
  STRING_TOO_LONG: 9008,
  STRING_TOO_SHORT: 9009,
  REQUIRED_FIELD_MISSING: 9010,
  DUPLICATE_VALUE: 9011,
  FOREIGN_KEY_CONSTRAINT: 9012,
  UNIQUE_CONSTRAINT: 9013
} as const;

// 合并所有错误码
export const ERROR_CODES = {
  ...COMMON_ERRORS,
  ...AUTH_ERRORS,
  ...USER_ERRORS,
  ...TASK_ERRORS,
  ...PAYMENT_ERRORS,
  ...DISTRIBUTION_ERRORS,
  ...SYSTEM_ERRORS,
  ...NETWORK_ERRORS,
  ...VALIDATION_ERRORS
} as const;

// 错误码分类
export const ERROR_CATEGORIES = {
  COMMON: 'common',
  AUTH: 'auth',
  USER: 'user',
  TASK: 'task',
  PAYMENT: 'payment',
  DISTRIBUTION: 'distribution',
  SYSTEM: 'system',
  NETWORK: 'network',
  VALIDATION: 'validation'
} as const;

// 错误严重程度
export const ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
} as const;

// 错误码到分类和严重程度的映射
export const ERROR_METADATA = {
  [ERROR_CODES.SUCCESS]: { category: ERROR_CATEGORIES.COMMON, severity: ERROR_SEVERITY.LOW },

  // 通用错误
  [ERROR_CODES.UNKNOWN_ERROR]: { category: ERROR_CATEGORIES.COMMON, severity: ERROR_SEVERITY.HIGH },
  [ERROR_CODES.INVALID_REQUEST]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.MISSING_PARAMETERS]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.INVALID_PARAMETERS]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: {
    category: ERROR_CATEGORIES.COMMON,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.CRITICAL
  },
  [ERROR_CODES.DATABASE_ERROR]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.CACHE_ERROR]: { category: ERROR_CATEGORIES.SYSTEM, severity: ERROR_SEVERITY.MEDIUM },
  [ERROR_CODES.QUEUE_ERROR]: { category: ERROR_CATEGORIES.SYSTEM, severity: ERROR_SEVERITY.HIGH },
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.HIGH
  },

  // 认证错误
  [ERROR_CODES.UNAUTHORIZED]: { category: ERROR_CATEGORIES.AUTH, severity: ERROR_SEVERITY.MEDIUM },
  [ERROR_CODES.INVALID_TOKEN]: { category: ERROR_CATEGORIES.AUTH, severity: ERROR_SEVERITY.MEDIUM },
  [ERROR_CODES.TOKEN_EXPIRED]: { category: ERROR_CATEGORIES.AUTH, severity: ERROR_SEVERITY.MEDIUM },
  [ERROR_CODES.TOKEN_BLACKLISTED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.INVALID_CREDENTIALS]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ACCOUNT_LOCKED]: { category: ERROR_CATEGORIES.AUTH, severity: ERROR_SEVERITY.HIGH },
  [ERROR_CODES.ACCOUNT_DISABLED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ACCOUNT_NOT_FOUND]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PASSWORD_INCORRECT]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.LOGIN_REQUIRED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // 登录错误
  [ERROR_CODES.LOGIN_ATTEMPTS_EXCEEDED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.LOGIN_METHOD_NOT_SUPPORTED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.LOGIN_METHOD_NOT_BOUND]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.VERIFICATION_CODE_INVALID]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.VERIFICATION_CODE_EXPIRED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.VERIFICATION_SEND_LIMIT]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PHONE_ALREADY_EXISTS]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.SOCIAL_LOGIN_FAILED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // 权限错误
  [ERROR_CODES.PERMISSION_DENIED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ROLE_NOT_FOUND]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ROLE_ASSIGNMENT_FAILED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: {
    category: ERROR_CATEGORIES.AUTH,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ADMIN_REQUIRED]: { category: ERROR_CATEGORIES.AUTH, severity: ERROR_SEVERITY.HIGH },

  // 用户错误
  [ERROR_CODES.USER_NOT_FOUND]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.USER_ALREADY_EXISTS]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.USER_PROFILE_INCOMPLETE]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.USER_QUOTA_EXCEEDED]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.USER_MEMBERSHIP_EXPIRED]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.USER_SUBSCRIPTION_INACTIVE]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.INVITE_CODE_INVALID]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.INVITE_CODE_USED]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.INVITE_CODE_EXPIRED]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.REFERRAL_CODE_INVALID]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.REFERRAL_NOT_FOUND]: {
    category: ERROR_CATEGORIES.USER,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // 任务错误
  [ERROR_CODES.TASK_NOT_FOUND]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.TASK_CREATION_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.TASK_PROCESSING_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.TASK_TIMEOUT]: { category: ERROR_CATEGORIES.TASK, severity: ERROR_SEVERITY.MEDIUM },
  [ERROR_CODES.TASK_CANCELLED]: { category: ERROR_CATEGORIES.TASK, severity: ERROR_SEVERITY.LOW },
  [ERROR_CODES.TASK_QUOTA_EXCEEDED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.TASK_INVALID_PARAMETERS]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.TASK_PROCESSOR_UNAVAILABLE]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.TASK_DEPENDENCY_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.TASK_RESULT_EXPIRED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.LOW
  },

  // 文件错误
  [ERROR_CODES.FILE_NOT_FOUND]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FILE_TOO_LARGE]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FILE_TYPE_NOT_SUPPORTED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FILE_UPLOAD_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.FILE_PROCESSING_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.FILE_DOWNLOAD_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FILE_CORRUPTED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.STORAGE_QUOTA_EXCEEDED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // AI处理错误
  [ERROR_CODES.AI_PROCESSING_FAILED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.AI_SERVICE_UNAVAILABLE]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.AI_QUOTA_EXCEEDED]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.AI_CONTENT_POLICY_VIOLATION]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.AI_PROCESSING_TIMEOUT]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.AI_INVALID_INPUT_FORMAT]: {
    category: ERROR_CATEGORIES.TASK,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // 支付错误
  [ERROR_CODES.PAYMENT_REQUIRED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PAYMENT_FAILED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.PAYMENT_CANCELLED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.PAYMENT_TIMEOUT]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PAYMENT_METHOD_NOT_SUPPORTED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ORDER_NOT_FOUND]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ORDER_EXPIRED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.ORDER_ALREADY_PAID]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.REFUND_FAILED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.REFUND_AMOUNT_INVALID]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PAYMENT_GATEWAY_ERROR]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.INSUFFICIENT_BALANCE]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PAYMENT_VERIFICATION_FAILED]: {
    category: ERROR_CATEGORIES.PAYMENT,
    severity: ERROR_SEVERITY.HIGH
  },

  // 分销错误
  [ERROR_CODES.DISTRIBUTOR_NOT_FOUND]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.DISTRIBUTION_NOT_ACTIVE]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.COMMISSION_CALCULATION_FAILED]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.WITHDRAWAL_FAILED]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.WITHDRAWAL_AMOUNT_INVALID]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.WITHDRAWAL_LIMIT_EXCEEDED]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.DISTRIBUTION_RULE_NOT_FOUND]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.COMMISSION_FREEZE_FAILED]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.COMMISSION_UNFREEZE_FAILED]: {
    category: ERROR_CATEGORIES.DISTRIBUTION,
    severity: ERROR_SEVERITY.HIGH
  },

  // 系统错误
  [ERROR_CODES.CONFIG_NOT_FOUND]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.CONFIG_VALIDATION_FAILED]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FEATURE_NOT_ENABLED]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.SYSTEM_MAINTENANCE]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.SERVICE_UNAVAILABLE]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.RATE_LIMIT_CONFIG_INVALID]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.CACHE_VERSION_CONFLICT]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.DATABASE_MIGRATION_FAILED]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.CRITICAL
  },
  [ERROR_CODES.ENVIRONMENT_VARIABLE_MISSING]: {
    category: ERROR_CATEGORIES.SYSTEM,
    severity: ERROR_SEVERITY.CRITICAL
  },

  // 网络错误
  [ERROR_CODES.CONNECTION_FAILED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.REQUEST_TIMEOUT]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.DNS_RESOLUTION_FAILED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.SSL_VERIFICATION_FAILED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.HIGH
  },
  [ERROR_CODES.PROXY_ERROR]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.BANDWIDTH_LIMIT_EXCEEDED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.WEBSOCKET_CONNECTION_FAILED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.NOTIFICATION_SEND_FAILED]: {
    category: ERROR_CATEGORIES.NETWORK,
    severity: ERROR_SEVERITY.MEDIUM
  },

  // 验证错误
  [ERROR_CODES.DATA_VALIDATION_FAILED]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.EMAIL_FORMAT_INVALID]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.PHONE_FORMAT_INVALID]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.PASSWORD_TOO_WEAK]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.PASSWORD_MISMATCH]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.URL_FORMAT_INVALID]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.DATE_FORMAT_INVALID]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.NUMBER_OUT_OF_RANGE]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.STRING_TOO_LONG]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.STRING_TOO_SHORT]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.LOW
  },
  [ERROR_CODES.REQUIRED_FIELD_MISSING]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.DUPLICATE_VALUE]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.FOREIGN_KEY_CONSTRAINT]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  },
  [ERROR_CODES.UNIQUE_CONSTRAINT]: {
    category: ERROR_CATEGORIES.VALIDATION,
    severity: ERROR_SEVERITY.MEDIUM
  }
} as const;

export type ErrorCodeKey = keyof typeof ERROR_CODES;
export type ErrorCode = (typeof ERROR_CODES)[ErrorCodeKey];
export type ErrorCategoryKey = keyof typeof ERROR_CATEGORIES;
export type ErrorCategory = (typeof ERROR_CATEGORIES)[ErrorCategoryKey];
export type ErrorSeverityKey = keyof typeof ERROR_SEVERITY;
export type ErrorSeverity = (typeof ERROR_SEVERITY)[ErrorSeverityKey];
